import os
import glob
import logging
import pandas
try:
    from database import get_cursor
except ImportError:
    from .database import get_cursor

logger = logging.getLogger(__name__)

def get_inventory_turnover(filters=None):
    """
    Calculates Inventory Turnover (Ratio and Days) for all items.
    Uses data from the last 30 days.
    """
    cursor = get_cursor()
    
    try:
        # Optimization: Read the pre-calculated report generated by turnover_calc.py
        # Find the latest report file
        REPORT_DIR = '/home/usman/onedrive_folder/project_data/turnover_reports/'
        report_files = glob.glob(os.path.join(REPORT_DIR, "inventory_turnover_*.parquet"))
        
        if not report_files:
            logger.warning("No pre-calculated turnover reports found. Falling back to empty.")
            return []
            
        latest_report = max(report_files, key=os.path.getmtime)
        logger.info(f"Using pre-calculated turnover report: {latest_report}")

        # Build filter clause for the pre-calculated data
        filter_clause = "1=1"
        if filters:
            clauses = []
            for col, values in filters.items():
                if values:
                    val_list = "', '".join([v.replace("'", "''") for v in values])
                    # Map filter names if needed (Product name -> product_name)
                    col_name = f'"{col}"' if ' ' in col else col
                    clauses.append(f"{col_name} IN ('{val_list}')")
            if clauses:
                filter_clause = " AND ".join(clauses)

        query = f"""
            SELECT 
                item_id,
                item_name,
                product_name,
                ROUND(avg_inventory, 2) as avg_stock,
                ROUND(current_stock, 2) as current_stock,
                total_sales,
                turnover_ratio,
                turnover_days
            FROM read_parquet('{latest_report}')
            WHERE {filter_clause}
            ORDER BY total_sales DESC
            LIMIT 1000
        """
        res = cursor.execute(query).fetchall()
        
        # Convert to list of dicts
        columns = ['item_id', 'item_name', 'product_name', 'avg_stock', 'current_stock', 'total_sales', 'turnover_ratio', 'turnover_days']
        return [dict(zip(columns, row)) for row in res]
        
    except Exception as e:
        logger.error(f"Error calculating inventory turnover: {e}")
        return {"error": str(e)}
