import os
import glob
import logging
import pandas
try:
    from database import get_cursor
except ImportError:
    from .database import get_cursor

logger = logging.getLogger(__name__)

def get_inventory_turnover(filters=None):
    """
    Calculates Inventory Turnover (Ratio and Days) for all items.
    Uses data from the last 30 days.
    """
    cursor = get_cursor()
    
    try:
        # Optimization: Read the pre-calculated report generated by turnover_calc.py
        # Find the latest report file
        REPORT_DIR = '/home/usman/onedrive_folder/project_data/turnover_reports/'
        report_files = glob.glob(os.path.join(REPORT_DIR, "inventory_turnover_*.parquet"))
        
        if not report_files:
            logger.warning("No pre-calculated turnover reports found. Falling back to empty.")
            return []
            
        latest_report = max(report_files, key=os.path.getmtime)
        logger.info(f"Using pre-calculated turnover report: {latest_report}")

        # Check columns in the parquet file to be safe
        file_columns = cursor.execute(f"SELECT * FROM read_parquet('{latest_report}') LIMIT 0").description
        existing_cols = [col[0] for col in file_columns]
        logger.info(f"Report columns: {existing_cols}")

        # Build filter clause safely
        filter_clause = "1=1"
        if filters:
            clauses = []
            for col, values in filters.items():
                if values:
                    # Map common frontend names to potential parquet names
                    target_col = col
                    if col not in existing_cols:
                        if col == 'Product name' and 'product_name' in existing_cols: target_col = 'product_name'
                        elif col == 'Category' and 'category' in existing_cols: target_col = 'category'
                        elif col == 'Category' and 'Category' in existing_cols: target_col = 'Category'
                    
                    if target_col in existing_cols:
                        val_list = "', '".join([str(v).replace("'", "''") for v in values])
                        clauses.append(f'"{target_col}" IN (\'{val_list}\')')
            if clauses:
                filter_clause = " AND ".join(clauses)

        query = f"""
            SELECT 
                item_id,
                item_name,
                product_name,
                ROUND(avg_inventory, 2) as avg_stock,
                ROUND(current_stock, 2) as current_stock,
                total_sales,
                turnover_ratio,
                turnover_days
            FROM read_parquet('{latest_report}')
            WHERE {filter_clause}
            ORDER BY total_sales DESC
            LIMIT 1000
        """
        res = cursor.execute(query).fetchall()
        
        # Convert to list of dicts
        columns = ['item_id', 'item_name', 'product_name', 'avg_stock', 'current_stock', 'total_sales', 'turnover_ratio', 'turnover_days']
        return [dict(zip(columns, row)) for row in res]
        
    except Exception as e:
        logger.error(f"Error in inventory turnover API: {e}", exc_info=True)
        return [] # Return empty list instead of error object to keep frontend alive
